### ISSUE TITLE
ValueError: expects 3 weights, but the saved weights have 2 elements.

### ISSUE THREAD

**Issue by nywang2019** [MathiasGruber/PConv-Keras#50]
I ran the code successfully on my laptop with 1 GPU,  however, while I try to try on remote workstaton with NVIDIA Tesla P100 GPU . it does not work. anyone can help me?  thanks.
-----------------------------------------------
Traceback (most recent call last):
  File "/home/irlts/nianyi/PConv-Keras-master/main.py", line 210, in <module>
    model.load(args.checkpoint)
  File "/home/irlts/nianyi/PConv-Keras-master/libs/pconv_model.py", line 271, in load
    self.model.load_weights(filepath)        
  File "/localscratch/irlts.21223938.0/env/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/localscratch/irlts.21223938.0/env/lib/python3.7/site-packages/keras/engine/network.py", line 1230, in load_weights
    f, self.layers, reshape=reshape)
  File "/localscratch/irlts.21223938.0/env/lib/python3.7/site-packages/keras/engine/saving.py", line 1235, in load_weights_from_hdf5_group
    ' elements.')
ValueError: Layer #0 (named "p_conv2d_17" in the current model) was found to correspond to layer p_conv2d_49 in the save file. However the new layer p_conv2d_17 expects 3 weights, but the saved weights have 2 elements.

**Comment by nywang2019** [comment]
I have resolved this problem.  it's because of tensorflow version.

**Comment by leeqiaogithub** [comment]
> I have resolved this problem. it's because of tensorflow version.

i have met the same error.do you know the reason why the version of tensorflow may cause this problem?

**Comment by nywang2019** [comment]
> > I have resolved this problem. it's because of tensorflow version.
> 
> i have met the same error.do you know the reason why the version of tensorflow may cause this problem?

i do not know the reason. just use different versions to test.

**Comment by Harisahmad1881** [comment]
which version did u use?

**Comment by nywang2019** [comment]
@Harisahmad1881 TF2.0

**Comment by divyanshj16** [comment]
is there a way to run this on TF2?
