### ISSUE TITLE
main() problem.

### ISSUE THREAD

**Issue by zhangbaijin** [MathiasGruber/PConv-Keras#53]
Found 0 images belonging to 0 classes.
Traceback (most recent call last):
  File "/home//PConv-Keras-master/main.py", line 180, in <module>
    test_data = next(test_generator)
  File "/home//PConv-Keras-master/main.py", line 122, in flow_from_directory
    for _ in range(ori.shape[0])], axis=0
  File "/home/zxf/anaconda3/envs/tensorflow/lib/python3.6/site-packages/numpy/core/shape_base.py", line 412, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

excuse me . I follow the comand  python main.py     --name celeba     --train ./data/celeba/train     --validation ./data/celeba/val     --test ./data/celeba/test     --vgg_path './data/logs/pytorch_to_keras_vgg16.h5'
 but  there is no found files about mask and image, why?? i put masks dataset under  ./data/masks/train/

**Comment by jiunyen-ching** [comment]
Are your images placed in a sub-folder in each train/test/val folder?
I assume your images are now placed like this:
Train: "./data/train/*.png"
Test: "./data/test/*.png"
Val: "./data/val/*.png"

where they should be placed like this
Train: "./data/train/**subdir_1**/*.png"
Test: "./data/test/**subdir_1**/*.png"
Val: "./data/val/**subdir_1**/*.png"

I guess number of subdirs in each train/test/val depends on your number of classes
